import Head from 'next/head'
import Link from "next/link";

import '../styles/globals.css'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Blogão</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-10 bg-gradient-to-r from-green-400 to-blue-500 text-center">
        <Link href="/">
          <h2 className="text-5xl font-bold text-white">Blogão versão 0.0.0.0.0.0.0.0.1</h2>
        </Link>
      </header>

      <main className="my-6 mx-auto p-6 bg-white sm:shadow-lg rounded prose lg:prose-xl">
        <Component {...pageProps} />
      </main>
    </>
  )
}
